### ISSUE TITLE
Markbot keeps asking for berries/index.html

### ISSUE THREAD

**Issue by jenn-sweet** [jenn-sweet/code-a-website#1]
@hellachella

Markbot keeps asking for the berries/index.html, I put the index in my berries folder, it hated it, took it out and left it in the main, it hated it. I have no idea where the bloody thing is suppose to go.

As of now, I have 
index.html
resources.html
berries.html
berries/blueberries.html (and the same for currants, bananas and grapes, they are all in the berries folder)

**Comment by hellachella** [comment]
Change berries.html to index.html (yep, a second one). Put it in the berries folder.
